//
//  AccountRouter.swift
//  TesteiOSv2
//
//  Created by Vitor Ferraz Varela on 23/07/19.
//  Copyright © 2019 Vitor Ferraz Varela. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AccountRoutingLogic {
    func routeToLogin()
}

final class AccountRouter: NSObject, AccountRoutingLogic, AccountDataPassing {
    var dataStore: AccountDataStore?
    weak var viewController: AccountViewController?
    
    func routeToLogin() {
        guard let accountViewController = self.viewController else { return }
        accountViewController.dismiss(animated: true, completion: nil)
    }
}
