//
//  LoginPresenter.swift
//  TesteiOSv2
//
//  Created by Vitor Ferraz Varela on 22/07/19.
//  Copyright © 2019 Vitor Ferraz Varela. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LoginPresentationLogic {
    func presentError(error: Error)
    func presentUserAccount(response: UserAccountResponse)
    func presentPersistedCredentials(response: Login)
}

final class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?

    func presentError(error: Error) {
        let viewModel = LoginViewModel(error: error)
        viewController?.displayError(viewModel: viewModel)
    }
    
    func presentUserAccount(response: UserAccountResponse) {
        viewController?.displayUserAccount()
    }
    
    func presentPersistedCredentials(response: Login) {
        let viewModel = LoginViewModel(user: response.user, password: response.password)
        viewController?.displayPersistedCredentials(viewModel: viewModel)
    }
    
    
}
