//
//  AccountPresenter.swift
//  TesteiOSv2
//
//  Created by Vitor Ferraz Varela on 23/07/19.
//  Copyright © 2019 Vitor Ferraz Varela. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic {
    func presentAccountDetails(response: UserAccountResponse)
    func presentStatements(response: StatementResponse)
    func presentError(error: Error)
}

final class AccountPresenter: AccountPresentationLogic {
  
    
    weak var viewController: AccountDisplayLogic?
    
    func presentAccountDetails(response: UserAccountResponse) {
        let viewModel = AccountViewModel(userAccount: response.userAccount)
        viewController?.displayAccountDetails(viewModel: viewModel)
    }
    
    func presentStatements(response: StatementResponse) {
        let list = response.statements.map({StatementViewModel.init(statement: $0)})
        viewController?.displayStatements(list: list)
    }
    
    func presentError(error: Error) {
        viewController?.presentError(error: error)
    }
}
