//
//  LoginRouter.swift
//  TesteiOSv2
//
//  Created by Vitor Ferraz Varela on 22/07/19.
//  Copyright © 2019 Vitor Ferraz Varela. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToAccount()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}
final class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToAccount() {
        let sb = UIStoryboard(name: "Main", bundle: nil)
        guard let accountViewController = sb.instantiateViewController(withIdentifier: "AccountViewController") as? AccountViewController else { fatalError()
        }
        accountViewController.setup()

        guard let loginViewController = self.viewController else {
                fatalError()
        }
        guard let sourceDataStore = self.dataStore else {
            fatalError()
        }
        accountViewController.viewModel = AccountViewModel(userAccount: sourceDataStore.userAccount!)
        navigateToAccount(source: loginViewController, destination: accountViewController)
    }
    
    // MARK: Navigation
    
    func navigateToAccount(source: LoginViewController, destination: AccountViewController) {
        source.navigationController?.present(destination, animated: true, completion: nil)
    }
}
